### ISSUE TITLE
Send Intel datasheet to Jared and Neil

### ISSUE THREAD

**Issue by prasnak** [turtledoves/turtledove-software#3]
If they can't find the details that they are looking for in the datasheet that you send, we'll have to consider buying the pc so....

Move issue to 'DONE' pipeline once done

**Comment by iwanttoeatyo** [comment]
MSI CUBI 001 Specs
010BEU-B3500UXX

https://us.msi.com/pdf/bb/Cubi-001BUS.pdf
http://www.intel.com/buy/us/en/product/desktop/msi-cubi-cubi-001bus-pc-488085/technical-specifications


https://www.msi.com/Desktop/Cubi.html#hero-overview
LOW POWER CONSUMPTION
This mini-PC is a true energy vanguard; in full loading the total power consumption is less than 30Watt, saving a lot of money on the energy bill.


http://www.kitguru.net/desktop-pc/leo-waldock/msi-cubi-review/
The thermal performance of Broadwell is deeply impressive. Our Core i3 Cubi drew 10W idling on the desktop and required 13W to run PC Mark 8. Under extreme load running benchmarks the peak power draw was 24W which makes a nonsense of the 65W external power adapter. The tiny amount of power produces the bare minimum of heat.

9-16v to 19v DC Converter
http://www.bixpower.com/BX-DD90M-p/bx-dd90m-19v.htm
