### ISSUE TITLE
Come up with task list for Navigation after discussing with Johannes

### ISSUE THREAD

**Issue by xiaxi203** [turtledoves/turtledove-software#7]
https://github.com/turtledoves/turtledove-software/issues/assigned/xiaxi203

**Comment by xiaxi203** [comment]
1. generate map with elevation at each pixel
2. determine the gradient at each pixel
3. determine constant cost factor for elevation
4. generate cost map
5. apply coarse grid A*

**Comment by prasnak** [comment]
Issue moved to [turtledoves/turtledove-navigation #1](https://github.com/turtledoves/turtledove-navigation/issues/1) via [**ZenHub.io**](https://www.zenhub.io/)
